import { StyleSheet } from 'react-native';
import { Colors } from '../colors';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingBottom: 8,
    backgroundColor: Colors.white,
  },
  iconBtn: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 17,
    fontWeight: '700',
    color: Colors.onSurface,
  },
  searchRow: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    backgroundColor: Colors.white,
  },
  searchBox: {
    height: 42,
    borderRadius: 10,
    backgroundColor: Colors.surfaceContainerLow,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    gap: 8,
  },
  searchInput: { flex: 1, fontSize: 14, color: Colors.onSurface },
  listBody: { padding: 16, gap: 10, paddingBottom: 120 },
  currentCard: {
    flexDirection: 'row',
    gap: 10,
    backgroundColor: Colors.white,
    borderRadius: 12,
    padding: 14,
    alignItems: 'flex-start',
    elevation: 1,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
  },
  sectionTitle: {
    marginTop: 8,
    fontSize: 13,
    fontWeight: '600',
    color: Colors.secondary,
  },
  row: {
    flexDirection: 'row',
    gap: 10,
    backgroundColor: Colors.white,
    borderRadius: 12,
    padding: 14,
    alignItems: 'flex-start',
  },
  cardLabel: { fontSize: 14, fontWeight: '700', color: Colors.onSurface },
  cardAddress: {
    fontSize: 12,
    color: Colors.onSurfaceVariant,
    marginTop: 2,
    lineHeight: 16,
  },
  editLink: {
    color: '#1A73E8',
    fontSize: 13,
    fontWeight: '600',
    paddingTop: 2,
  },
  empty: {
    textAlign: 'center',
    color: Colors.textSecondary,
    marginTop: 24,
  },
  footer: {
    padding: 16,
    backgroundColor: Colors.white,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: Colors.outlineVariant,
  },
  addBtn: {
    backgroundColor: Colors.primary,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
  },
  addBtnText: { color: Colors.white, fontSize: 15, fontWeight: '700' },
  guestBox: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 32,
    gap: 10,
  },
  guestTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: Colors.onSurface,
    textAlign: 'center',
  },
  guestSub: {
    fontSize: 13,
    color: Colors.onSurfaceVariant,
    textAlign: 'center',
    marginBottom: 12,
  },
  loginBtn: {
    marginTop: 8,
    paddingVertical: 12,
    paddingHorizontal: 24,
  },
  loginBtnText: {
    color: Colors.primary,
    fontWeight: '700',
    fontSize: 15,
  },
});
