import { StyleSheet } from 'react-native';
import { Colors } from '../colors';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  body: { flex: 1 },
  bodyContent: { padding: 16, paddingBottom: 160, gap: 20 },
  section: { gap: 8 },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  sectionLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: Colors.onSurfaceVariant,
    letterSpacing: 0.8,
  },
  changeBtn: { fontSize: 12, fontWeight: '700', color: Colors.primary },
  addressActions: { flexDirection: 'row', gap: 14 },
  miniMap: {
    height: 140,
    borderRadius: 14,
    overflow: 'hidden',
  },
  addressCard: {
    flexDirection: 'row',
    backgroundColor: Colors.white,
    padding: 14,
    borderRadius: 14,
    gap: 12,
  },
  addressIcon: {
    backgroundColor: Colors.primaryFixed,
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addressInfo: { flex: 1, gap: 2 },
  addressTitle: { fontSize: 15, fontWeight: '700', color: Colors.onSurface },
  addressText: { fontSize: 13, color: Colors.onSurfaceVariant },
  emptyCart: {
    alignItems: 'center',
    paddingVertical: 32,
    gap: 8,
    backgroundColor: Colors.white,
    borderRadius: 14,
  },
  emptyCartText: { fontSize: 15, fontWeight: '600', color: Colors.onSurface },
  browseBtn: {
    marginTop: 8,
    backgroundColor: Colors.primaryFixed,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 999,
  },
  browseBtnText: { color: Colors.primary, fontWeight: '700' },
  itemsCard: {
    backgroundColor: Colors.white,
    borderRadius: 14,
    overflow: 'hidden',
  },
  cartItem: {
    flexDirection: 'row',
    padding: 12,
    gap: 12,
    alignItems: 'center',
  },
  cartItemBorder: { borderBottomWidth: 1, borderBottomColor: Colors.outlineVariant },
  itemImage: { width: 60, height: 60, borderRadius: 8 },
  itemInfo: { flex: 1, gap: 6 },
  itemName: { fontSize: 14, fontWeight: '600', color: Colors.onSurface },
  itemBottom: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  itemPrice: { fontSize: 14, fontWeight: '700', color: Colors.primary },
  stepper: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  stepBtn: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: Colors.surfaceContainerHigh,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepValue: { fontSize: 14, fontWeight: '600', minWidth: 16, textAlign: 'center' },
  noteInput: {
    backgroundColor: Colors.white,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
    color: Colors.onSurface,
  },
  paymentGrid: { flexDirection: 'row', gap: 10 },
  paymentCard: {
    flex: 1,
    backgroundColor: Colors.white,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: Colors.outlineVariant,
    padding: 14,
    alignItems: 'center',
    gap: 6,
  },
  paymentActive: { borderColor: Colors.primary, borderWidth: 2 },
  paymentLabel: { fontSize: 13, fontWeight: '600' },
  summaryCard: {
    backgroundColor: Colors.white,
    borderRadius: 14,
    padding: 14,
    gap: 10,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  summaryText: { fontSize: 14, color: Colors.onSurfaceVariant },
  discountText: { fontSize: 14, color: Colors.primary },
  discountValue: { fontSize: 14, fontWeight: '600', color: Colors.primary },
  voucherHint: { fontSize: 12, color: Colors.secondary },
  voucherOk: { fontSize: 12, color: Colors.primary, fontWeight: '600' },
  voucherFail: { fontSize: 12, color: '#C62828', marginTop: 2 },
  voucherInputRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
  },
  voucherInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: Colors.outlineVariant,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    fontWeight: '600',
    color: Colors.onSurface,
  },
  voucherApplyBtn: {
    backgroundColor: Colors.primary,
    borderRadius: 10,
    paddingHorizontal: 14,
    justifyContent: 'center',
  },
  voucherApplyText: { color: Colors.white, fontWeight: '700', fontSize: 13 },
  sheetItemDisabled: { opacity: 0.55 },
  totalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: Colors.outlineVariant,
    paddingTop: 10,
  },
  totalLabel: { fontSize: 16, fontWeight: '700' },
  totalValue: { fontSize: 18, fontWeight: '700', color: Colors.primary },
  footer: {
    backgroundColor: Colors.white,
    borderTopWidth: 1,
    borderTopColor: Colors.outlineVariant,
    paddingHorizontal: 16,
    paddingTop: 12,
    gap: 10,
  },
  promoBtn: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  promoText: { fontSize: 13, fontWeight: '600', color: Colors.primary },
  orderBtn: {
    backgroundColor: Colors.primary,
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
  },
  orderBtnDisabled: { opacity: 0.5 },
  orderBtnText: { color: Colors.white, fontSize: 16, fontWeight: '700' },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-end',
  },
  sheet: {
    backgroundColor: Colors.white,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
    maxHeight: '72%',
  },
  sheetTitle: { fontSize: 17, fontWeight: '700', marginBottom: 12 },
  sheetItem: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: Colors.outlineVariant,
  },
  sheetItemTitle: { fontSize: 15, fontWeight: '600', color: Colors.onSurface },
  sheetItemSub: { fontSize: 12, color: Colors.secondary, marginTop: 2 },
  sheetEmpty: { color: Colors.secondary, paddingVertical: 20 },
});
