import { StyleSheet } from 'react-native';
import { Colors } from '../colors';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  heroWrap: { height: 200 },
  hero: { flex: 1 },
  heroGradient: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.35)',
  },
  heroHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
  },
  heroBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0,0,0,0.35)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    backgroundColor: Colors.primary,
    borderRadius: 8,
    minWidth: 16,
    height: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroBadgeText: { color: Colors.white, fontSize: 10, fontWeight: '700' },
  heroContent: { position: 'absolute', left: 16, bottom: 16, right: 16 },
  popularBadge: {
    alignSelf: 'flex-start',
    backgroundColor: Colors.primary,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    marginBottom: 6,
  },
  popularText: { color: Colors.white, fontSize: 10, fontWeight: '700' },
  heroTitle: { color: Colors.white, fontSize: 22, fontWeight: '700' },
  statsCard: {
    marginTop: -16,
    marginHorizontal: 16,
    backgroundColor: Colors.white,
    borderRadius: 14,
    flexDirection: 'row',
    paddingVertical: 12,
    zIndex: 2,
  },
  statItem: { flex: 1, alignItems: 'center', gap: 2 },
  statBorder: {
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor: Colors.outlineVariant,
  },
  statValue: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  statNumber: { fontSize: 14, fontWeight: '700', color: Colors.onSurface },
  statLabel: { fontSize: 11, color: Colors.secondary },
  searchWrap: {
    marginHorizontal: 16,
    marginTop: 12,
    backgroundColor: Colors.white,
    borderRadius: 999,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    height: 40,
    gap: 8,
  },
  searchInput: { flex: 1, fontSize: 14, color: Colors.onSurface },
  categoryNav: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 8,
  },
  categoryChip: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: Colors.white,
    marginRight: 8,
  },
  categoryChipActive: { backgroundColor: Colors.primary },
  categoryChipText: {
    fontSize: 13,
    fontWeight: '600',
    color: Colors.onSurfaceVariant,
  },
  categoryChipTextActive: { color: Colors.white },
  sectionBlock: { gap: 10, marginBottom: 8 },
  sectionLabel: { fontSize: 16, fontWeight: '700', color: Colors.onSurface },
  menuLoading: { padding: 40, alignItems: 'center' },
  menuError: { color: Colors.primary },
  menuList: { padding: 16, paddingBottom: 120, gap: 10 },
  listItem: {
    flexDirection: 'row',
    backgroundColor: Colors.white,
    borderRadius: 14,
    padding: 10,
    gap: 10,
    alignItems: 'center',
  },
  listImageWrap: { position: 'relative' },
  listImage: { width: 72, height: 72, borderRadius: 10 },
  discountBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    backgroundColor: Colors.red,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 999,
  },
  discountBadgeText: { color: Colors.white, fontSize: 10, fontWeight: '700' },
  listInfo: { flex: 1, gap: 3 },
  listName: { fontSize: 14, fontWeight: '700', color: Colors.onSurface },
  listDesc: { fontSize: 12, color: Colors.secondary },
  priceRow: { flexDirection: 'row', alignItems: 'baseline', gap: 6 },
  listPrice: { fontSize: 14, fontWeight: '700', color: Colors.primary },
  listOriginalPrice: {
    fontSize: 12,
    color: Colors.textLight,
    textDecorationLine: 'line-through',
  },
  qtyCol: { alignItems: 'center' },
  addCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: Colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepper: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  stepBtn: {
    width: 26,
    height: 26,
    borderRadius: 8,
    backgroundColor: Colors.primaryFixed,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepVal: { minWidth: 16, textAlign: 'center', fontWeight: '700' },
  cartBar: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 16,
    backgroundColor: Colors.primary,
    borderRadius: 14,
    padding: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  cartLabel: { color: Colors.white, fontWeight: '600' },
  cartTotal: { color: Colors.white, fontWeight: '700' },
  modalBg: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'flex-end',
  },
  sheet: {
    backgroundColor: Colors.white,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 20,
  },
  sheetImage: {
    width: '100%',
    height: 160,
    borderRadius: 12,
    marginBottom: 12,
  },
  sheetName: { fontSize: 18, fontWeight: '700', color: Colors.onSurface },
  sheetDesc: { fontSize: 13, color: Colors.secondary, marginTop: 6 },
  sheetRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: 16,
  },
  sheetPrice: { fontSize: 18, fontWeight: '700', color: Colors.primary },
  sheetBtn: {
    backgroundColor: Colors.primary,
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
  },
  sheetBtnText: { color: Colors.white, fontWeight: '700', fontSize: 16 },
  reviewsSection: { marginTop: 8, gap: 10 },
  reviewsTitle: { fontSize: 16, fontWeight: '700', color: Colors.onSurface },
  reviewsEmpty: { fontSize: 13, color: Colors.secondary, paddingVertical: 8 },
  reviewCard: {
    backgroundColor: Colors.white,
    borderRadius: 12,
    padding: 12,
    gap: 6,
  },
  reviewHeader: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  reviewAvatar: { width: 36, height: 36, borderRadius: 18 },
  reviewHeaderInfo: { flex: 1, gap: 2 },
  reviewName: { fontSize: 13, fontWeight: '700', color: Colors.onSurface },
  reviewStars: { flexDirection: 'row', gap: 1 },
  reviewDate: { fontSize: 11, color: Colors.textLight },
  reviewComment: { fontSize: 13, color: Colors.onSurfaceVariant, lineHeight: 18 },
  reviewsMoreBtn: { alignItems: 'center', paddingVertical: 10 },
  reviewsMoreText: { color: Colors.primary, fontWeight: '700', fontSize: 13 },
});
