/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-125998-g2a20737f66-20260809"
#endif /* AVUTIL_FFVERSION_H */
